rainforest/config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

  root :to => 'products#index'



end

rainforest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rainforest/app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price_in_cents, presence: true
  validates :price_in_cents, numericality: true

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

  has_many :reviews


end

rainforest/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :comment, presence: true
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def create
    @product = Product.new

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    if @product.save
      redirect_to products_path
    else
      render :new
    end
    flash.notice = "You added a new product to our store, Fantastic!"
  end

  def new
    @product = Product.new

  end

  def index
    @products = Product.all

  end

  def show
    @product = Product.find(params[:id])

    @review = @product.reviews.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    if @product.save
      redirect_to products_path
    else
      render :edit
    end
    flash.notice = "You edited a product, Gold Star!!!"
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_path
    else
      render :show
    end
    flash.notice = "Good Job, little buddy you deleted a product."
  end





end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    @review.comment = params[:review][:comment]
    if @review.save
      redirect_to product_path(params[:product_id])
    else
      render "products/show"
    end
  end

  def edit



    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render "reviews/edit_product_review"



  end

  def update
    @review = Review.find(params[:id])
    @review.comment = params[:review][:comment]
    @product = Product.find(params[:product_id])
    if @review.save
      redirect_to product_path(params[:product_id])
    else
      render "reviews/edit_product_review"
    end

  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to product_path(params[:product_id])
    else
      render :show
    end

  end

end


#This comes when you click on create comment
#params={"utf8"=>"✓",
#  "authenticity_token"=>"aTi4RqJRtc5mTK345EtRCHNDAiGNfWLpHNeudgHzT6UBBGTiT0lASqjr1p4jLabzmFgYySTSv3IisDPgRLh/Tw==",
#  "review"=>{"comment"=>"great vacuum lots of fun\r\n"},
#  "commit"=>"Create Review",
#  "product_id"=>"10"}

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="nav">
      <%= link_to " HOME" , products_path %> 
      <%= link_to "New Product Page", new_product_path %>
    </nav>

    <% if flash[:notice] %>
    <p class="notice"> <%= flash[:notice]%></p>
    <% end %>

    <% if flash[:alert] %>
    <p class="alert"> <%= flash[:alert]%> </p>
    <% end %>


    <%= yield %>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>

</html>

rainforest/app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>

<p><%= f.label :description %></p>
<p><%= f.text_area :description %></p>

<p><%= f.label :price_in_cents %></p>
<p><%= f.text_field :price_in_cents %></p>
<p><%= f.submit "SUBMIT" %></p>
<% end %>

rainforest/app/views/products/edit.html.erb
<h1>Edit a Product</h1>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %>! You're an idiot, you can't edit a simple product:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= render 'form.html.erb' %>


<%= link_to "Show Page", product_path(@product) %>

rainforest/app/views/products/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Product Homepage</h1>

  </div>
</div>


<div class="jumbotron jumbotron-fluid2">
  <div class="container">

      <div class="card" style="width: 100%;">
      <div class="card-body">
      <p><% @products.each do |product| %></p>

      <h4 class="card-title"> <%= product.name %></h4>


      <p class="card-text">
      <li><%= product.price_in_dollars %></li>
      <li><%= product.description  %></li>

      <button type="button" class="btn btn-outline-primary">
      <%= link_to("Take a Look", "/products/#{product.id}") %></button>

      </p>





     <% end %>
     </div>
   </div>

  </div>

    <button type="button" class="btn btn-primary btn-lg btn-block"><%= link_to "Create NEW!", new_product_path %></button>

rainforest/app/views/products/new.html.erb
<h1>New Product</h1>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %>! You're an idiot, you can't complete a simple form:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form.html.erb' %>

rainforest/app/views/products/show.html.erb
<h1>Product Show Page</h1>
<p><%= @product.name %></p>
<p><%= @product.description %></p>
<p><%= @product.price_in_dollars %></p>

<%= link_to "Edit", edit_product_path(@product)%> |
<%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Hmmmmmmm, are you certain?"} %>
<hr>
<% if !@product.reviews.empty? %>
  <% @product.reviews.each do |review| %>
    <% if review.persisted? %>
      <%= review.comment %> <br>
      <% p review %>
      <%= review.created_at %>
      <%= link_to "Edit", edit_product_review_path(product_id:@product.id, id:review.id)%> <hr>
    <% end %>
  <% end %>


<% end %>

<h4>New Review</h4>

<%= render "reviews/form.html.erb" %>

rainforest/app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rainforest/app/views/reviews/edit_product_review.html.erb
<%= render "reviews/form.html.erb" %>
<%= link_to("Delete Review", product_review_path(@product, @review), method: :delete, data: {confirm: "Are you sure"}) %>